# Generated by Django 4.2.13 on 2024-05-21 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findClass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roomii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('end_time', models.DateTimeField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodfoms', to='findClass.building')),
            ],
        ),
    ]
