# Generated by Django 4.2.13 on 2024-05-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findClass', '0002_roomii'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roomii',
        ),
    ]
